### ISSUE TITLE
Turn into single app repo

### ISSUE THREAD

**Issue by jasny** [ltonetwork/lto-wallet#101]
Remove the explorer from this repository. We have a new explorer, the one in this repo is no longer used.

Preferably turn this into a normal Angular single app project.

**Comment by brunodb3** [comment]
Explorer has been removed, it is now hosted on https://github.com/ltonetwork/lto-network-explorer

**Comment by brunodb3** [comment]
Branch created: https://github.com/ltonetwork/lto-ui/tree/cleanup
