### ISSUE TITLE
Anchor transactions not visible after signing with Ledger

### ISSUE THREAD

**Issue by justmvg** [ltonetwork/lto-wallet#187]
Anchoring a hash of a file works fine using a Ledger device, but the transaction is not visible under "Active anchors" after it's fully processed.

![image](https://user-images.githubusercontent.com/36076579/133274113-9d18b34e-4537-4865-90db-413bfef4036f.png)

![image](https://user-images.githubusercontent.com/36076579/133274129-fb55cf1f-64d2-41fa-871f-a3e35f8163c2.png)

**Comment by justmvg** [comment]
> After a bit of digging, found that the error is not with the wallet UI, but with the configuration of the Testnet Node. When it gets fixed, I will close this issue.

Hi Bruno, was this resolved and can this be closed?

**Comment by brunodb3** [comment]
It should have been resolved a while ago, I guess I forgot to close the issue 😅 

I'm closing it now, if it happens again, just reopen and someone will pick it up 👍
